__version__      = '0.5.2'
__description__  = 'Utilities for working with Church Slavonic language'
__keywords__     = 'church slavonic language'
__url__          = 'https://github.com/pgmmpk/cslavonic'
__author__       = 'Mike Kroutikov'
__author_email__ = 'pgmmpk@gmail.com'
